services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'youtube-scrapper'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "hiteshwadhwani1403@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - '5050:80'
    depends_on:
      - db


volumes:
  postgres-data:
    
