services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'youtube-scrapper'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my_network
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - '5050:80'
    depends_on:
      - db
  
  main:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my_network

volumes:
  postgres-data:
    
networks:
  my_network:
    driver: bridge